# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 11:56
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.PositiveIntegerField()),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Params')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Assigned'), (2, 'Done'), (3, 'Timeout')], default=0, verbose_name='Status')),
                ('result', models.CharField(max_length=64, verbose_name='Result')),
                ('result_data', models.CharField(max_length=64, verbose_name='Result data')),
                ('agentid', models.CharField(max_length=32, verbose_name='Agent ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created')),
                ('finished', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Finished')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Priority')),
            ],
        ),
    ]
