# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 12:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Params'),
        ),
    ]
