# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20171012_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='taskid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
