# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20171012_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Params'),
        ),
    ]
